image: continuumio/miniconda3:latest

before_script:
- conda config --add channels conda-forge 
- conda create -n sage python=2
- source activate sage
- conda install sage=8.1
- git clone https://github.com/sagemath/sage.git sagemath
- cd sagemath

tests:
  stage: test
  artifacts:
    paths:
    - doctest.out
    when: always
  script:
  - git checkout 8.1
  - sage -tp src/ > doctest.out
