image: continuumio/miniconda3:latest

before_script:

- conda config --add channels conda-forge
- conda create -n sage sage=8.2 python=2 sphinx jmol pillow twisted
- source activate sage
- git clone https://github.com/sagemath/sage.git sagemath
- cd sagemath


tests:
  stage: test
  artifacts:
    paths:
    - sagemath/doctest.txt
    - sagemath/doctest.summary.txt
    when: always
  script:
  - git checkout 8.2
  - sage -tp src/ > doctest.txt || true
  - conda list '^sagelib$'
  - conda list '^sage$'
  - cat doctest.txt | grep '^sage -t ' | grep '#' > doctest.summary.txt || true
  - conda install -y bc
  - echo `cat doctest.summary.txt | awk '{ print $5 }' | sort | grep -E '[0-9]+' | paste -sd+ | bc` failing individual doctests
  - cat doctest.summary.txt | awk '{ print $5 }' | sort | grep -vE '[0-9]+' | sort | uniq -c || true
