image: condaforge/linux-anvil:latest

before_script:
- ./install_sage.sh

tests:
  stage: test
  artifacts:
    paths:
    - sagemath/doctest.txt
    - sagemath/doctest.summary.txt
    - sagemath/temp_folder.tar.gz
    when: always
  script:
  - ./test_sage.sh
