version: 2
jobs:
  test:
    docker:
      - image: condaforge/linux-anvil
    steps:
      - checkout
      - run: ./install_sage.sh
      - run: ./test_sage.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
